In [20]:
import pandas as pd
import numpy as np
import panel as pn
pn.extension('tabulator')

import hvplot.pandas

In [21]:
df = pd.read_csv("https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv")

In [22]:
if 'data' not in pn.state.cache.keys():
    df = pd.read_csv('https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv')
    
    pn.state.cache['data'] = df.copy()
    
else:
    df = pn.state.cache['data']

In [23]:
df

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,0.002,NaN,NaN,NaN,0.015,0.002,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,0.011,NaN,NaN,NaN,0.021,0.003,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,0.012,NaN,NaN,NaN,0.026,0.003,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,0.012,NaN,NaN,NaN,0.032,0.004,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001732e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,0.013,NaN,NaN,NaN,0.038,0.005,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25186,ZWE,Zimbabwe,2016,10.738,0.765,1.415,0.639,0.046,6.959,0.496,...,2.076,11.50,0.820,6.21,0.443,14030338.0,2.096179e+10,47.5,3385.574,1.889
25187,ZWE,Zimbabwe,2017,9.582,0.673,1.666,0.678,0.048,5.665,0.398,...,2.023,11.62,0.816,6.35,0.446,14236599.0,2.194784e+10,NaN,NaN,NaN
25188,ZWE,Zimbabwe,2018,11.854,0.821,1.308,0.697,0.048,7.101,0.492,...,2.173,11.96,0.828,6.59,0.456,14438812.0,2.271535e+10,NaN,NaN,NaN
25189,ZWE,Zimbabwe,2019,10.949,0.748,1.473,0.697,0.048,6.020,0.411,...,NaN,NaN,NaN,NaN,NaN,14645473.0,NaN,NaN,NaN,NaN
25190,ZWE,Zimbabwe,2020,10.531,0.709,NaN,0.697,0.047,6.257,0.421,...,NaN,NaN,NaN,NaN,NaN,14862927.0,NaN,NaN,NaN,NaN

In [24]:
df[df['country'] == 'North America']

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
16178,NaN,North America,1785,0.004,NaN,NaN,NaN,NaN,0.004,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16179,NaN,North America,1786,0.004,NaN,NaN,NaN,NaN,0.004,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16180,NaN,North America,1787,0.004,NaN,NaN,NaN,NaN,0.004,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16181,NaN,North America,1788,0.004,NaN,NaN,NaN,NaN,0.004,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16182,NaN,North America,1789,0.004,NaN,NaN,NaN,NaN,0.004,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,NaN,North America,2016,6471.360,11.353,309.904,70.858,0.124,1509.631,2.648,...,NaN,NaN,NaN,NaN,NaN,573814461.0,NaN,31594.441,87878.289,NaN
16410,NaN,North America,2017,6412.982,11.155,335.009,72.914,0.127,1467.602,2.553,...,NaN,NaN,NaN,NaN,NaN,578582963.0,NaN,31759.844,87748.432,NaN
16411,NaN,North America,2018,6588.630,11.366,345.915,74.787,0.129,1398.979,2.413,...,NaN,NaN,NaN,NaN,NaN,582921781.0,NaN,32718.297,89812.397,NaN
16412,NaN,North America,2019,6460.726,11.056,354.353,76.925,0.132,1214.329,2.078,...,NaN,NaN,NaN,NaN,NaN,587512621.0,NaN,32384.360,88336.805,NaN
16413,NaN,North America,2020,5775.159,9.805,NaN,76.870,0.130,965.430,1.639,...,NaN,NaN,NaN,NaN,NaN,592062319.0,NaN,NaN,NaN,NaN

In [25]:
df[df['country'] == 'World']

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
24660,OWID_WRL,World,1750,9.351,0.012,NaN,NaN,NaN,9.351,0.012,...,NaN,NaN,NaN,NaN,NaN,7.456644e+08,NaN,NaN,NaN,NaN
24661,OWID_WRL,World,1751,9.351,NaN,NaN,NaN,NaN,9.351,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24662,OWID_WRL,World,1752,9.354,NaN,NaN,NaN,NaN,9.354,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24663,OWID_WRL,World,1753,9.354,NaN,NaN,NaN,NaN,9.354,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24664,OWID_WRL,World,1754,9.358,NaN,NaN,NaN,NaN,9.358,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24926,OWID_WRL,World,2016,35452.459,4.750,-0.0,1478.758,0.198,14360.628,1.924,...,6.184,8172.01,1.095,3027.74,0.406,7.464344e+09,1.071343e+14,152944.938,20490.955,1.429
24927,OWID_WRL,World,2017,35925.738,4.760,0.0,1500.493,0.199,14453.702,1.915,...,6.197,8228.64,1.090,3078.27,0.408,7.548183e+09,1.104307e+14,155672.784,20624.761,NaN
24928,OWID_WRL,World,2018,36646.140,4.802,-0.0,1566.740,0.205,14718.145,1.929,...,6.238,8298.27,1.089,3063.75,0.402,7.631091e+09,1.136302e+14,160063.686,20975.203,NaN
24929,OWID_WRL,World,2019,36702.503,4.758,0.0,1608.472,0.208,14573.219,1.889,...,NaN,NaN,NaN,NaN,NaN,7.713468e+09,NaN,162194.290,21027.415,NaN
24930,OWID_WRL,World,2020,34807.259,4.465,0.0,1626.371,0.209,13976.098,1.793,...,NaN,NaN,NaN,NaN,NaN,7.794799e+09,NaN,NaN,NaN,NaN

In [26]:
df

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,0.002,NaN,NaN,NaN,0.015,0.002,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,0.011,NaN,NaN,NaN,0.021,0.003,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,0.012,NaN,NaN,NaN,0.026,0.003,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,0.012,NaN,NaN,NaN,0.032,0.004,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001732e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,0.013,NaN,NaN,NaN,0.038,0.005,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25186,ZWE,Zimbabwe,2016,10.738,0.765,1.415,0.639,0.046,6.959,0.496,...,2.076,11.50,0.820,6.21,0.443,14030338.0,2.096179e+10,47.5,3385.574,1.889
25187,ZWE,Zimbabwe,2017,9.582,0.673,1.666,0.678,0.048,5.665,0.398,...,2.023,11.62,0.816,6.35,0.446,14236599.0,2.194784e+10,NaN,NaN,NaN
25188,ZWE,Zimbabwe,2018,11.854,0.821,1.308,0.697,0.048,7.101,0.492,...,2.173,11.96,0.828,6.59,0.456,14438812.0,2.271535e+10,NaN,NaN,NaN
25189,ZWE,Zimbabwe,2019,10.949,0.748,1.473,0.697,0.048,6.020,0.411,...,NaN,NaN,NaN,NaN,NaN,14645473.0,NaN,NaN,NaN,NaN
25190,ZWE,Zimbabwe,2020,10.531,0.709,NaN,0.697,0.047,6.257,0.421,...,NaN,NaN,NaN,NaN,NaN,14862927.0,NaN,NaN,NaN,NaN

In [27]:
df = df.fillna(0)
df['gdp_per_capita'] = np.where(df['population']!= 0, df['gdp']/ df['population'], 0)

In [32]:
idf = df.interactive()

In [34]:
continents = ['World', 'Asia', 'Oceania', 'Europe', 'Africa', 'North America', 'South America', 'Antarctica']

In [50]:
df.to_csv("data.csv")

In [52]:
df.aggregate

<bound method DataFrame.aggregate of       iso_code      country  year     co2  co2_per_capita  trade_co2  \
0          AFG  Afghanistan  1949   0.015           0.002      0.000
1          AFG  Afghanistan  1950   0.084           0.011      0.000
2          AFG  Afghanistan  1951   0.092           0.012      0.000
3          AFG  Afghanistan  1952   0.092           0.012      0.000
4          AFG  Afghanistan  1953   0.106           0.013      0.000
...        ...          ...   ...     ...             ...        ...
25186      ZWE     Zimbabwe  2016  10.738           0.765      1.415
25187      ZWE     Zimbabwe  2017   9.582           0.673      1.666
25188      ZWE     Zimbabwe  2018  11.854           0.821      1.308
25189      ZWE     Zimbabwe  2019  10.949           0.748      1.473
25190      ZWE     Zimbabwe  2020  10.531           0.709      0.000

       cement_co2  cement_co2_per_capita  coal_co2  coal_co2_per_capita  ...  \
0           0.000                  0.000     0.015                0.002  ...
1           0.000                  0.000     0.021                0.003  ...
2           0.000                  0.000     0.026                0.003  ...
3           0.000                  0.000     0.032                0.004  ...
4           0.000                  0.000     0.038                0.005  ...
...           ...                    ...       ...                  ...  ...
25186       0.639                  0.046     6.959                0.496  ...
25187       0.678                  0.048     5.665                0.398  ...
25188       0.697                  0.048     7.101                0.492  ...
25189       0.697                  0.048     6.020                0.411  ...
25190       0.697                  0.047     6.257                0.421  ...

       methane  methane_per_capita  nitrous_oxide  nitrous_oxide_per_capita  \
0         0.00               0.000           0.00                     0.000
1         0.00               0.000           0.00                     0.000
2         0.00               0.000           0.00                     0.000
3         0.00               0.000           0.00                     0.000
4         0.00               0.000           0.00                     0.000
...        ...                 ...            ...                       ...
25186    11.50               0.820           6.21                     0.443
25187    11.62               0.816           6.35                     0.446
25188    11.96               0.828           6.59                     0.456
25189     0.00               0.000           0.00                     0.000
25190     0.00               0.000           0.00                     0.000

       population           gdp  primary_energy_consumption  \
0       7624058.0  0.000000e+00                         0.0
1       7752117.0  9.421400e+09                         0.0
2       7840151.0  9.692280e+09                         0.0
3       7935996.0  1.001732e+10                         0.0
4       8039684.0  1.063052e+10                         0.0
...           ...           ...                         ...
25186  14030338.0  2.096179e+10                        47.5
25187  14236599.0  2.194784e+10                         0.0
25188  14438812.0  2.271535e+10                         0.0
25189  14645473.0  0.000000e+00                         0.0
25190  14862927.0  0.000000e+00                         0.0

       energy_per_capita  energy_per_gdp  gdp_per_capita
0                  0.000           0.000        0.000000
1                  0.000           0.000     1215.332534
2                  0.000           0.000     1236.236394
3                  0.000           0.000     1262.264371
4                  0.000           0.000     1322.255949
...                  ...             ...             ...
25186           3385.574           1.889     1494.033492
25187              0.000           0.000     1541.648897
25188              0.000           0.000     1573.214856
25189              0.000           0.000        0.000000
25190              0.000           0.000        0.000000

[25191 rows x 61 columns]>